### ISSUE TITLE
New maintainer/CRAN check fixes

### ISSUE THREAD

**Issue by leeper** [leeper/webuse#5]
The current errors reported by CRAN are documented here: https://cran.r-project.org/web/checks/check_results_webuse.html

The Github version is slightly ahead of CRAN, so it may be possible that they're already fixed. Try [winbuilder](https://win-builder.r-project.org/upload.aspx). If not, the easiest thing might be just to kill (some of) the examples and tests.

With that, it's all yours @jodibeggs! Thanks again for taking this over!

**Comment by jodibeggs** [comment]
I think the problem was caused by http redirecting to https in windows so I changed the former to the latter and that should resolve the issue.  *fingers crossed*
